"""Add weights to CustomGoalProfile

Revision ID: 234958dacb66
Revises: 72323602ae8d
Create Date: 2026-09-02 23:56:38.465426
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234958dacb66'
down_revision: Union[str, None] = '72323602ae8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_goal_profiles', sa.Column('weights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_goal_profiles', 'weights')
    # ### end Alembic commands ###
