"""Add AI Report Feedback

Revision ID: 2e93f85edc46
Revises: 3b164bdce3ee
Create Date: 2026-09-01 23:37:18.527195
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e93f85edc46'
down_revision: Union[str, None] = '3b164bdce3ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
