"""Initial schema

Revision ID: 3b164bdce3ee
Revises: 
Create Date: 2026-08-29 00:23:22.822526
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b164bdce3ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('function', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('common_uses', sa.JSON(), nullable=True),
    sa.Column('potential_benefits', sa.JSON(), nullable=True),
    sa.Column('potential_concerns', sa.JSON(), nullable=True),
    sa.Column('population_considerations', sa.JSON(), nullable=True),
    sa.Column('regulatory_status', sa.JSON(), nullable=True),
    sa.Column('is_common_allergen', sa.Boolean(), nullable=True),
    sa.Column('allergen_group', sa.String(length=100), nullable=True),
    sa.Column('evidence_strength', sa.Enum('VERY_HIGH', 'HIGH', 'MODERATE', 'LIMITED', 'VERY_LIMITED', 'UNKNOWN', name='evidencestrength'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_canonical_name'), 'ingredients', ['canonical_name'], unique=True)
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('serving_size', sa.String(length=100), nullable=True),
    sa.Column('serving_unit', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'USER_SUBMITTED', 'PARTIALLY_VERIFIED', 'VERIFIED', name='verificationstatus'), nullable=True),
    sa.Column('data_quality', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNKNOWN', name='dataquality'), nullable=True),
    sa.Column('data_source_tier', sa.Enum('MANUFACTURER', 'VERIFIED_DB', 'RETAIL_PROVIDER', 'USER_SUBMITTED', 'COMMUNITY_CORRECTION', name='datasourcetier'), nullable=True),
    sa.Column('external_source', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index('ix_products_brand_name', 'products', ['brand', 'name'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('USER', 'EXPERT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('data_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_tier', sa.Enum('MANUFACTURER', 'VERIFIED_DB', 'RETAIL_PROVIDER', 'USER_SUBMITTED', 'COMMUNITY_CORRECTION', name='datasourcetier'), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('license_info', sa.String(length=500), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_provenance_id'), 'data_provenance', ['id'], unique=False)
    op.create_table('ingredient_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_aliases_alias_name'), 'ingredient_aliases', ['alias_name'], unique=False)
    op.create_index(op.f('ix_ingredient_aliases_id'), 'ingredient_aliases', ['id'], unique=False)
    op.create_table('ingredient_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=100), nullable=True),
    sa.Column('population', sa.String(length=255), nullable=True),
    sa.Column('evidence_strength', sa.Enum('VERY_HIGH', 'HIGH', 'MODERATE', 'LIMITED', 'VERY_LIMITED', 'UNKNOWN', name='evidencestrength'), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('contradictory_evidence', sa.Boolean(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_claims_id'), 'ingredient_claims', ['id'], unique=False)
    op.create_table('nutrition_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('serving_size', sa.String(length=100), nullable=True),
    sa.Column('serving_unit', sa.String(length=50), nullable=True),
    sa.Column('energy_kcal', sa.Float(), nullable=True),
    sa.Column('total_fat_g', sa.Float(), nullable=True),
    sa.Column('saturated_fat_g', sa.Float(), nullable=True),
    sa.Column('trans_fat_g', sa.Float(), nullable=True),
    sa.Column('cholesterol_mg', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('total_carbohydrates_g', sa.Float(), nullable=True),
    sa.Column('dietary_fiber_g', sa.Float(), nullable=True),
    sa.Column('total_sugars_g', sa.Float(), nullable=True),
    sa.Column('added_sugars_g', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('vitamin_a_mcg', sa.Float(), nullable=True),
    sa.Column('vitamin_c_mg', sa.Float(), nullable=True),
    sa.Column('vitamin_d_mcg', sa.Float(), nullable=True),
    sa.Column('calcium_mg', sa.Float(), nullable=True),
    sa.Column('iron_mg', sa.Float(), nullable=True),
    sa.Column('potassium_mg', sa.Float(), nullable=True),
    sa.Column('additional_nutrients', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_nutrition_facts_id'), 'nutrition_facts', ['id'], unique=False)
    op.create_table('privacy_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allow_anonymous_context_sharing', sa.Boolean(), nullable=True),
    sa.Column('share_age_range', sa.Boolean(), nullable=True),
    sa.Column('share_dietary_pattern', sa.Boolean(), nullable=True),
    sa.Column('share_activity_level', sa.Boolean(), nullable=True),
    sa.Column('share_goals', sa.Boolean(), nullable=True),
    sa.Column('share_allergies', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_privacy_settings_id'), 'privacy_settings', ['id'], unique=False)
    op.create_table('product_allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('allergen', sa.String(length=100), nullable=False),
    sa.Column('certainty', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_allergens_id'), 'product_allergens', ['id'], unique=False)
    op.create_table('product_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('claim', sa.String(length=500), nullable=False),
    sa.Column('claim_type', sa.String(length=100), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_claims_id'), 'product_claims', ['id'], unique=False)
    op.create_table('product_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('identifier_type', sa.String(length=50), nullable=False),
    sa.Column('identifier_value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_identifiers_id'), 'product_identifiers', ['id'], unique=False)
    op.create_index(op.f('ix_product_identifiers_identifier_value'), 'product_identifiers', ['identifier_value'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.create_table('product_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('is_allergen', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_ingredients_id'), 'product_ingredients', ['id'], unique=False)
    op.create_table('product_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('ingredients_text', sa.Text(), nullable=True),
    sa.Column('nutrition_snapshot', sa.JSON(), nullable=True),
    sa.Column('allergens_snapshot', sa.JSON(), nullable=True),
    sa.Column('changes_from_previous', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_versions_id'), 'product_versions', ['id'], unique=False)
    op.create_table('saved_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_products_id'), 'saved_products', ['id'], unique=False)
    op.create_table('user_allergies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allergen', sa.String(length=100), nullable=False),
    sa.Column('allergy_type', sa.Enum('ALLERGY', 'INTOLERANCE', 'PREFERENCE', name='allergytype'), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_allergies_id'), 'user_allergies', ['id'], unique=False)
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_goals_id'), 'user_goals', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preference_type', sa.String(length=100), nullable=False),
    sa.Column('is_hard_constraint', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.Enum('SEDENTARY', 'LIGHTLY_ACTIVE', 'MODERATELY_ACTIVE', 'VERY_ACTIVE', 'EXTREMELY_ACTIVE', name='activitylevel'), nullable=True),
    sa.Column('dietary_pattern', sa.Enum('OMNIVORE', 'VEGETARIAN', 'VEGAN', 'EGGETARIAN', 'PESCATARIAN', 'KETO', 'OTHER', name='dietarypattern'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('community_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_version_id', sa.Integer(), nullable=True),
    sa.Column('usage_duration', sa.Enum('ONCE', 'FEW_DAYS', 'FEW_WEEKS', 'SEVERAL_MONTHS', 'MORE_THAN_A_YEAR', name='usageduration'), nullable=False),
    sa.Column('experience_type', sa.Enum('NO_NOTICEABLE_EFFECT', 'POSITIVE', 'NEGATIVE', 'DIGESTIVE_DISCOMFORT', 'SKIN_REACTION', 'HEADACHE', 'ENERGY_CHANGE', 'APPETITE_CHANGE', 'OTHER', name='experiencetype'), nullable=False),
    sa.Column('experience_text', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.String(length=255), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('not_helpful_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_version_id'], ['product_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_reviews_id'), 'community_reviews', ['id'], unique=False)
    op.create_table('review_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('dietary_pattern', sa.String(length=50), nullable=True),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('relevant_allergies', sa.JSON(), nullable=True),
    sa.Column('usage_duration', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['community_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    op.create_index(op.f('ix_review_contexts_id'), 'review_contexts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_contexts_id'), table_name='review_contexts')
    op.drop_table('review_contexts')
    op.drop_index(op.f('ix_community_reviews_id'), table_name='community_reviews')
    op.drop_table('community_reviews')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_goals_id'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_user_allergies_id'), table_name='user_allergies')
    op.drop_table('user_allergies')
    op.drop_index(op.f('ix_saved_products_id'), table_name='saved_products')
    op.drop_table('saved_products')
    op.drop_index(op.f('ix_product_versions_id'), table_name='product_versions')
    op.drop_table('product_versions')
    op.drop_index(op.f('ix_product_ingredients_id'), table_name='product_ingredients')
    op.drop_table('product_ingredients')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_product_identifiers_identifier_value'), table_name='product_identifiers')
    op.drop_index(op.f('ix_product_identifiers_id'), table_name='product_identifiers')
    op.drop_table('product_identifiers')
    op.drop_index(op.f('ix_product_claims_id'), table_name='product_claims')
    op.drop_table('product_claims')
    op.drop_index(op.f('ix_product_allergens_id'), table_name='product_allergens')
    op.drop_table('product_allergens')
    op.drop_index(op.f('ix_privacy_settings_id'), table_name='privacy_settings')
    op.drop_table('privacy_settings')
    op.drop_index(op.f('ix_nutrition_facts_id'), table_name='nutrition_facts')
    op.drop_table('nutrition_facts')
    op.drop_index(op.f('ix_ingredient_claims_id'), table_name='ingredient_claims')
    op.drop_table('ingredient_claims')
    op.drop_index(op.f('ix_ingredient_aliases_id'), table_name='ingredient_aliases')
    op.drop_index(op.f('ix_ingredient_aliases_alias_name'), table_name='ingredient_aliases')
    op.drop_table('ingredient_aliases')
    op.drop_index(op.f('ix_data_provenance_id'), table_name='data_provenance')
    op.drop_table('data_provenance')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index('ix_products_brand_name', table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_canonical_name'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
