"""Add CustomGoalProfile

Revision ID: 72323602ae8d
Revises: d486534c1e25
Create Date: 2026-09-02 01:14:57.976686
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72323602ae8d'
down_revision: Union[str, None] = 'd486534c1e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_goal_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('prefer_low', sa.JSON(), nullable=False),
    sa.Column('prefer_high', sa.JSON(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_goal_profiles_goal_type'), 'custom_goal_profiles', ['goal_type'], unique=True)
    op.create_index(op.f('ix_custom_goal_profiles_id'), 'custom_goal_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_goal_profiles_id'), table_name='custom_goal_profiles')
    op.drop_index(op.f('ix_custom_goal_profiles_goal_type'), table_name='custom_goal_profiles')
    op.drop_table('custom_goal_profiles')
    # ### end Alembic commands ###
